# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.tag import Tag
from swagger_server import util


class TargetImage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, tile_image_urls: List[str]=None, tags: List[Tag]=None):  # noqa: E501
        """TargetImage - a model defined in Swagger

        :param id: The id of this TargetImage.  # noqa: E501
        :type id: int
        :param name: The name of this TargetImage.  # noqa: E501
        :type name: str
        :param tile_image_urls: The tile_image_urls of this TargetImage.  # noqa: E501
        :type tile_image_urls: List[str]
        :param tags: The tags of this TargetImage.  # noqa: E501
        :type tags: List[Tag]
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'tile_image_urls': List[str],
            'tags': List[Tag]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'tile_image_urls': 'tileImageUrls',
            'tags': 'tags'
        }

        self._id = id
        self._name = name
        self._tile_image_urls = tile_image_urls
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'TargetImage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TargetImage of this TargetImage.  # noqa: E501
        :rtype: TargetImage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this TargetImage.


        :return: The id of this TargetImage.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this TargetImage.


        :param id: The id of this TargetImage.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this TargetImage.


        :return: The name of this TargetImage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TargetImage.


        :param name: The name of this TargetImage.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def tile_image_urls(self) -> List[str]:
        """Gets the tile_image_urls of this TargetImage.


        :return: The tile_image_urls of this TargetImage.
        :rtype: List[str]
        """
        return self._tile_image_urls

    @tile_image_urls.setter
    def tile_image_urls(self, tile_image_urls: List[str]):
        """Sets the tile_image_urls of this TargetImage.


        :param tile_image_urls: The tile_image_urls of this TargetImage.
        :type tile_image_urls: List[str]
        """
        if tile_image_urls is None:
            raise ValueError("Invalid value for `tile_image_urls`, must not be `None`")  # noqa: E501

        self._tile_image_urls = tile_image_urls

    @property
    def tags(self) -> List[Tag]:
        """Gets the tags of this TargetImage.


        :return: The tags of this TargetImage.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[Tag]):
        """Sets the tags of this TargetImage.


        :param tags: The tags of this TargetImage.
        :type tags: List[Tag]
        """

        self._tags = tags
